import type { Metadata } from "next"
import localFont from "next/font/local"
import { Providers } from "./providers"
// import { Provider } from "./components/ui/provider"
import { Footer } from "./footer"
import "./globals.css"
import { Suspense } from "react"

const geistSans = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--font-PJS-Normal",
  weight: "100 400",
});
const geistMono = localFont({
  src: "./fonts/PlusJakartaSans-Bold.ttf",
  variable: "--font-PJS-Bold",
  weight: "500 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
