import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers"
import "./globals.css";
import { Footer } from "./footer"

const geistSans = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--font-PJS-Normal",
  weight: "100 400",
});
const geistMono = localFont({
  src: "./fonts/PlusJakartaSans-Bold.ttf",
  variable: "--font-PJS-Bold",
  weight: "500 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
